"""add the ip address & drop table notification prefernces

Revision ID: 2984dd75f35e
Revises: c84877b203da
Create Date: 2026-06-09 14:51:20.993647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2984dd75f35e'
down_revision: Union[str, Sequence[str], None] = 'c84877b203da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_devices",sa.Column("ip_address",sa.String(length=45),nullable=True,comment="IP address from which the device was used"))
    op.add_column("user_devices",sa.Column("last_accessed_ip",sa.String(length=45),nullable=True,comment="IP address of previous access"))
    op.add_column("user_devices",sa.Column("session_id",sa.String(length=36),nullable=True,comment="FK -> user_sessions.id(SET NULL on delete)"))
    op.create_foreign_key(
        "fk_user_devices_session_id",
        source_table="user_devices",
        referent_table="user_sessions",
        local_cols=["session_id"],
        remote_cols=["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_user_devices_session_id",
        "user_devices",
        ["session_id"],
        unique=False,
    )
    # Notification
    op.execute("""
ALTER TABLE users
ADD COLUMN IF NOT EXISTS notification_preferences JSON
DEFAULT '{"email": true, "push": true, "inApp": true}'
NOT NULL
""")
    try:
        op.drop_table("user_notification_preferences")
    except Exception:  # pragma: no cover
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_notification_preferences",
        sa.Column("id", sa.Integer, primary_key=True),
    )

    op.drop_column("users", "notification_preferences")

    op.drop_index("ix_user_devices_session_id", table_name="user_devices")
    op.drop_constraint("fk_user_devices_session_id", "user_devices", type_="foreignkey")
    op.drop_column("user_devices", "session_id")
    op.drop_column("user_devices", "last_accessed_ip")
    op.drop_column("user_devices", "ip_address")
    
    op.alter_column(
        "users",
        "registration_type",
        new_column_name="login_type",
        existing_type=sa.String(length=30),
        nullable=False,
    )
    # ### end Alembic commands ###
