"""add is_onboarding to user

Revision ID: 32293d02ec0b
Revises: 74bd36f52e39
Create Date: 2026-06-09 19:31:04.011243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32293d02ec0b'
down_revision: Union[str, Sequence[str], None] = '74bd36f52e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_comments_author_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_depth'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_moderation_status'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_parent_comment_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_post_id'), table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_index(op.f('ix_post_engagements_post_id'), table_name='post_engagements')
    op.drop_index(op.f('ix_post_engagements_reaction'), table_name='post_engagements')
    op.drop_index(op.f('ix_post_engagements_user_id'), table_name='post_engagements')
    op.drop_table('post_engagements')
    op.drop_index(op.f('uq_daily_analytics_date'), table_name='daily_analytics')
    op.create_unique_constraint('uq_daily_analytics_date', 'daily_analytics', ['date'])
    op.create_index(op.f('ix_daily_analytics_id'), 'daily_analytics', ['id'], unique=False)
    op.drop_column('email_otps', 'is_expire')
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    op.alter_column('user_devices', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='IP address from which the device was used',
               existing_nullable=True)
    op.alter_column('user_devices', 'last_accessed_ip',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='IP address of previous access',
               existing_nullable=True)
    op.alter_column('user_devices', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='FK -> user_sessions.id(SET NULL on delete)',
               existing_nullable=True)
    op.drop_index(op.f('uq_user_devices_device_token'), table_name='user_devices')
    op.create_unique_constraint('uq_user_devices_device_token', 'user_devices', ['device_token'])
    op.add_column('users', sa.Column('is_onboarding', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_column('users', 'login_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_type', sa.VARCHAR(length=30), server_default=sa.text("'email'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_onboarding')
    op.drop_constraint('uq_user_devices_device_token', 'user_devices', type_='unique')
    op.create_index(op.f('uq_user_devices_device_token'), 'user_devices', ['device_token'], unique=True)
    op.alter_column('user_devices', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               comment='FK -> user_sessions.id(SET NULL on delete)',
               existing_nullable=True)
    op.alter_column('user_devices', 'last_accessed_ip',
               existing_type=sa.VARCHAR(length=45),
               comment='IP address of previous access',
               existing_nullable=True)
    op.alter_column('user_devices', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='IP address from which the device was used',
               existing_nullable=True)
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.add_column('email_otps', sa.Column('is_expire', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_daily_analytics_id'), table_name='daily_analytics')
    op.drop_constraint('uq_daily_analytics_date', 'daily_analytics', type_='unique')
    op.create_index(op.f('uq_daily_analytics_date'), 'daily_analytics', ['date'], unique=True)
    op.create_table('post_engagements',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('reaction', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('is_liked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('post_engagements_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('post_engagements_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('post_engagements_pkey')),
    sa.UniqueConstraint('post_id', 'user_id', name=op.f('uq_post_engagement_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_post_engagements_user_id'), 'post_engagements', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_engagements_reaction'), 'post_engagements', ['reaction'], unique=False)
    op.create_index(op.f('ix_post_engagements_post_id'), 'post_engagements', ['post_id'], unique=False)
    op.create_table('post_comments',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('parent_comment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('depth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('moderation_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('moderation_reasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('post_comments_author_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['post_comments.id'], name=op.f('post_comments_parent_comment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('post_comments_post_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('post_comments_pkey'))
    )
    op.create_index(op.f('ix_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_comments_parent_comment_id'), 'post_comments', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_post_comments_moderation_status'), 'post_comments', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_post_comments_id'), 'post_comments', ['id'], unique=False)
    op.create_index(op.f('ix_post_comments_depth'), 'post_comments', ['depth'], unique=False)
    op.create_index(op.f('ix_post_comments_author_id'), 'post_comments', ['author_id'], unique=False)
    # ### end Alembic commands ###
