"""remove is_expire field

Revision ID: c6ad758dd864
Revises: 2984dd75f35e
Create Date: 2026-06-09 16:36:31.136263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6ad758dd864'
down_revision: Union[str, Sequence[str], None] = '2984dd75f35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DO $$
        BEGIN
            -- Verify the column is present before trying to drop it
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = 'email_otps'
                  AND column_name = 'is_expire'
            ) THEN
                ALTER TABLE email_otps DROP COLUMN is_expire;
            END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###