"""add registration_type to users

Revision ID: c84877b203da
Revises: 47f07776e05b_usertable_changes
Create Date: 2026-06-09 14:37:06.600771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c84877b203da'
down_revision: Union[str, Sequence[str], None] = '47f07776e05b_usertable_changes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users",sa.Column("registration_type",sa.String(length=30),nullable=True))
    op.execute("""UPDATE users SET registration_type=login_type""")
    op.alter_column("users","registration_type",nullable=False)
    op.drop_column("users","login_type")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembi)c - please adjust! ###
    op.add_column("users",sa.Column("login_type",sa.String(length=30),nullable=True))
    op.execute("""UPDATE users SET login_type=registration_type""")
    op.alter_column("users","login_type",nullable=False)

    op.drop_column("users","registration_type")

    # ### end Alembic commands ###
